# Generated by Django 4.2.11 on 2024-05-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='timestamp',
        ),
    ]
