# Generated by Django 4.2.11 on 2024-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
